// AUTO-GENERATED from 五大表_Global_B2B_V2.xlsx by ingest_xlsx.py
// Real data only. Dates normalized; 05 rows -> one current-state outreach activity each.
export const SEED_STATE = {
 "prospects": [
  {
   "id": "c_001",
   "name": "Mountain Shop",
   "market": "美国",
   "region": "OR(俄勒冈州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "极致轻量/硬核性能",
   "scale": "中",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "mountainshop.net",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-01",
   "channel": "邮箱/contact form",
   "touch_count": 1,
   "batch": "alpha",
   "last_sent": "2026-07-01",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "mountainshop.net",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_001_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-01",
     "touchCount": 1
    },
    {
     "key": "ch_seed_c_001_1",
     "name": "Contact Form",
     "available": "yes",
     "discoveredAt": "2026-07-01",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_002",
   "name": "Ascent Outdoors",
   "market": "美国",
   "region": "WA(华盛顿州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "精致生活/氛围美学",
   "scale": "中",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "ascentoutdoors.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-01",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "alpha",
   "last_sent": "2026-07-01",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "ascentoutdoors.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_002_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-01",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_003",
   "name": "Feral Mountain Co.",
   "market": "美国",
   "region": "CO(科罗拉多州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "高性价比/大众通路",
   "scale": "中",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "liveferal.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "alpha",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "liveferal.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_003_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_004",
   "name": "Neptune Mountaineering",
   "market": "美国",
   "region": "CO(科罗拉多州)",
   "segment": "独立买手店 (精品/潮流)",
   "style_fit": "精致生活/氛围美学",
   "scale": "极高",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "neptunemountaineering.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "alpha",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立买手店 (精品/潮流)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "neptunemountaineering.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_004_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_005",
   "name": "JAX Outdoor Gear",
   "market": "美国",
   "region": "CO(科罗拉多州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "硬核混搭",
   "scale": "极高",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "jaxgoods.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "alpha",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "jaxgoods.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_005_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_006",
   "name": "Foster Outdoor",
   "market": "美国",
   "region": "OR(俄勒冈州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "高性价比/大众通路",
   "scale": "中",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "fosteroutdoor.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "beta",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "fosteroutdoor.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_006_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_007",
   "name": "Mountain Hardware & Sports",
   "market": "美国",
   "region": "CA(加利福尼亚州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "高性价比/大众通路",
   "scale": "中",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "mountainhardwareandsports.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "beta",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "mountainhardwareandsports.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_007_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_008",
   "name": "Happy Hiker",
   "market": "美国",
   "region": "NM(新墨西哥州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "精致生活/氛围美学",
   "scale": "低",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "happyhiker.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "beta",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "happyhiker.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_008_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_009",
   "name": "Slim Pickins Outfitters",
   "market": "美国",
   "region": "TX(得克萨斯州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "精致生活/氛围美学",
   "scale": "低",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "slimpickinsoutfitters.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "beta",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "slimpickinsoutfitters.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_009_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_010",
   "name": "Pack Rat Outdoor Center",
   "market": "美国",
   "region": "AR(阿肯色州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "精致生活/氛围美学",
   "scale": "低",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "packratoc.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "beta",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "packratoc.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_010_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_011",
   "name": "Trailful Outdoor Co.",
   "market": "美国",
   "region": "GA(佐治亚州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "精致生活/氛围美学",
   "scale": "低",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "trailful.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "beta",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "trailful.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_011_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_012",
   "name": "J&H Outdoors",
   "market": "美国",
   "region": "KY(肯塔基州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "精致生活/氛围美学",
   "scale": "低",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "jhoutdoors.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "beta",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "jhoutdoors.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_012_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_013",
   "name": "Sportago",
   "market": "美国",
   "region": "CA(加利福尼亚州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "精致生活/氛围美学",
   "scale": "低",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "sportago.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "beta",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "sportago.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_013_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_014",
   "name": "Proof Lab Outdoor Center",
   "market": "美国",
   "region": "CA(加利福尼亚州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "精致生活/氛围美学",
   "scale": "中",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "prooflab.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "beta",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "prooflab.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_014_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_015",
   "name": "Stoked",
   "market": "美国",
   "region": "IA(爱荷华州)",
   "segment": "独立零售店 (大众/杂货)",
   "style_fit": "高性价比/大众通路",
   "scale": "低",
   "status": "初次触达/未回",
   "source": "公司历史数据",
   "owner": "陈晨",
   "website": "stokeddsm.com",
   "quoted": false,
   "sampled": false,
   "first_contact": "2026-07-02",
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "beta",
   "last_sent": "2026-07-02",
   "remark": "",
   "customerType": "独立零售店 (大众/杂货)",
   "sourceMethod": "公司历史数据",
   "fitNote": "",
   "url": "stokeddsm.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_015_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-07-02",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_038",
   "name": "Anaconda Stores",
   "market": "澳大利亚",
   "region": "",
   "segment": "大型连锁卖场",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://www.anacondastores.com",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Facebook、邮件",
   "touch_count": 2,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "大型连锁卖场"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://www.anacondastores.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_038_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    },
    {
     "key": "ch_seed_c_038_1",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_039",
   "name": "BCF - Boating, Camping, Fishing",
   "market": "澳大利亚",
   "region": "",
   "segment": "独立零售店（大众/杂货）",
   "style_fit": "",
   "scale": "",
   "status": "已建立联系/意向沟通",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://www.bcf.com.au",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Facebook、邮件",
   "touch_count": 2,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "独立零售店（大众",
    "杂货）"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://www.bcf.com.au",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_039_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    },
    {
     "key": "ch_seed_c_039_1",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_040",
   "name": "Snowys Outdoors",
   "market": "澳大利亚",
   "region": "",
   "segment": "独立零售店（大众/杂货）",
   "style_fit": "",
   "scale": "",
   "status": "不匹配/归档",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://www.snowys.com.au",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "instagram、邮箱",
   "touch_count": 2,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "独立零售店（大众",
    "杂货）"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://www.snowys.com.au",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_040_0",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    },
    {
     "key": "ch_seed_c_040_1",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "现在没有扩展品牌的想法，不感兴趣，不要再发信息",
   "replyReason": "拒绝"
  },
  {
   "id": "c_041",
   "name": "paddy_pallin",
   "market": "澳大利亚",
   "region": "",
   "segment": "轻量化专卖店",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://www.paddypallin.com.au",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "instagram",
   "touch_count": 1,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "轻量化专卖店"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://www.paddypallin.com.au",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_041_0",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_042",
   "name": "mitchellsadventure",
   "market": "澳大利亚",
   "region": "",
   "segment": "军事化战术风格",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://www.mitchellsadventure.com",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "instagram",
   "touch_count": 1,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "军事化战术风格"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://www.mitchellsadventure.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_042_0",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_043",
   "name": "tentworldaus",
   "market": "澳大利亚",
   "region": "",
   "segment": "大型连锁卖场",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://www.tentworld.com.au",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "instagram",
   "touch_count": 2,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "大型连锁卖场"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://www.tentworld.com.au",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_043_0",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_044",
   "name": "mountain_equipment_aus",
   "market": "澳大利亚",
   "region": "",
   "segment": "轻量化专卖店",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://mountainequipment.com",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "instagram",
   "touch_count": 1,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "轻量化专卖店"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://mountainequipment.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_044_0",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_045",
   "name": "Trek & Travel",
   "market": "澳大利亚",
   "region": "",
   "segment": "轻量化专卖店",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://www.trekandtravel.com.au",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "instagram、网站",
   "touch_count": 1,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "轻量化专卖店"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://www.trekandtravel.com.au",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_045_0",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 1
    },
    {
     "key": "ch_seed_c_045_1",
     "name": "Website",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_046",
   "name": "Kathmandu",
   "market": "澳大利亚",
   "region": "",
   "segment": "自己的品牌",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://www.kathmandu.com.au",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "邮件",
   "touch_count": 1,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "自己的品牌"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://www.kathmandu.com.au",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_046_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_047",
   "name": "Camping Country Superstore",
   "market": "澳大利亚",
   "region": "",
   "segment": "独立零售店（大众/杂货）",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://campingcountry.com.au",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "邮件",
   "touch_count": 1,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "独立零售店（大众",
    "杂货）"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://campingcountry.com.au",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_047_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_048",
   "name": "PAST Outdoors",
   "market": "澳大利亚",
   "region": "",
   "segment": "大型连锁卖场, 轻量化专卖店",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://pastoutdoors.com",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Instgram、邮件",
   "touch_count": 2,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "大型连锁卖场",
    "轻量化专卖店"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://pastoutdoors.com",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_048_0",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    },
    {
     "key": "ch_seed_c_048_1",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_049",
   "name": "Macpac",
   "market": "澳大利亚",
   "region": "",
   "segment": "自己的品牌",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Facebook、ins、邮件",
   "touch_count": 2,
   "batch": "",
   "last_sent": "2026-15-53",
   "remark": "",
   "customerType": [
    "自己的品牌"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_049_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    },
    {
     "key": "ch_seed_c_049_1",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    },
    {
     "key": "ch_seed_c_049_2",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_050",
   "name": "Ultralight Gear",
   "market": "澳大利亚",
   "region": "",
   "segment": "轻量化专卖店",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Facebook、邮件",
   "touch_count": 2,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "轻量化专卖店"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_050_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    },
    {
     "key": "ch_seed_c_050_1",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_051",
   "name": "Camping World Australia",
   "market": "澳大利亚",
   "region": "",
   "segment": "独立零售店（大众/杂货）",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://compleatangler.com.au/pages/camping-world",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "邮箱",
   "touch_count": 1,
   "batch": "",
   "last_sent": "2026-16-15",
   "remark": "",
   "customerType": [
    "独立零售店（大众",
    "杂货）"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://compleatangler.com.au/pages/camping-world",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_051_0",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 1
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_052",
   "name": "Adventure Merchants and Outfitters",
   "market": "澳大利亚",
   "region": "",
   "segment": "改装/越野中心, 独立零售店（大众/杂货）",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Facebook、邮箱",
   "touch_count": 2,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "改装",
    "越野中心",
    "独立零售店（大众",
    "杂货）"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_052_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    },
    {
     "key": "ch_seed_c_052_1",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_053",
   "name": "Frontier - adventure at its core",
   "market": "澳大利亚",
   "region": "",
   "segment": "独立零售店（大众/杂货）, 轻量化专卖店",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://www.thefrontier.com.au/",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Facebook、邮箱",
   "touch_count": 2,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "独立零售店（大众",
    "杂货）",
    "轻量化专卖店"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://www.thefrontier.com.au/",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_053_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    },
    {
     "key": "ch_seed_c_053_1",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_054",
   "name": "Diamantina Outdoors",
   "market": "澳大利亚",
   "region": "",
   "segment": "自己的品牌",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://diamantina.net.au/",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Facebook、邮箱",
   "touch_count": 2,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "自己的品牌"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://diamantina.net.au/",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_054_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    },
    {
     "key": "ch_seed_c_054_1",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_055",
   "name": "The Outdoor Gear Co.",
   "market": "澳大利亚",
   "region": "",
   "segment": "军事化战术风格, 自己的品牌",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://www.outdoorgearcompany.com.au",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Facebook、instgram、邮箱",
   "touch_count": 3,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "军事化战术风格",
    "自己的品牌"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://www.outdoorgearcompany.com.au",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_055_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    },
    {
     "key": "ch_seed_c_055_1",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    },
    {
     "key": "ch_seed_c_055_2",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_056",
   "name": "Hiking Food Australia",
   "market": "澳大利亚",
   "region": "",
   "segment": "自己的品牌, 轻量化专卖店",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://www.hikingfood.com.au/",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Facebook、instgram、邮箱",
   "touch_count": 3,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "自己的品牌",
    "轻量化专卖店"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://www.hikingfood.com.au/",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_056_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    },
    {
     "key": "ch_seed_c_056_1",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    },
    {
     "key": "ch_seed_c_056_2",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_057",
   "name": "23zeroaustralia",
   "market": "澳大利亚",
   "region": "",
   "segment": "自己的品牌, 改装/越野中心",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "https://23zero.com.au/product-category/camping-furniture/",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Facebook、instgram、邮箱",
   "touch_count": 3,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "自己的品牌",
    "改装",
    "越野中心"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "https://23zero.com.au/product-category/camping-furniture/",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_057_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    },
    {
     "key": "ch_seed_c_057_1",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    },
    {
     "key": "ch_seed_c_057_2",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_058",
   "name": "Oz Off Road",
   "market": "澳大利亚",
   "region": "",
   "segment": "改装/越野中心, 独立零售店（大众/杂货）",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "Facebook、instgram，邮件",
   "touch_count": 3,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "改装",
    "越野中心",
    "独立零售店（大众",
    "杂货）"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_058_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    },
    {
     "key": "ch_seed_c_058_1",
     "name": "Instagram",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    },
    {
     "key": "ch_seed_c_058_2",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 3
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  },
  {
   "id": "c_059",
   "name": "Blackhawk",
   "market": "澳大利亚",
   "region": "",
   "segment": "独立零售店（大众/杂货）, 自己的品牌",
   "style_fit": "",
   "scale": "",
   "status": "初次触达/未回",
   "source": "客户信息表",
   "owner": "时菊",
   "website": "",
   "quoted": false,
   "sampled": false,
   "first_contact": null,
   "channel": "facebook、邮件",
   "touch_count": 2,
   "batch": "",
   "last_sent": null,
   "remark": "",
   "customerType": [
    "独立零售店（大众",
    "杂货）",
    "自己的品牌"
   ],
   "sourceMethod": "客户信息表",
   "fitNote": "",
   "url": "",
   "domain": "",
   "discovered_at": null,
   "channels": [
    {
     "key": "ch_seed_c_059_0",
     "name": "Facebook",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    },
    {
     "key": "ch_seed_c_059_1",
     "name": "Email",
     "available": "yes",
     "discoveredAt": "2026-01-01",
     "touchCount": 2
    }
   ],
   "updatedAt": null,
   "next_follow": null,
   "feedback": "",
   "replyReason": null
  }
 ],
 "contacts": [
  {
   "id": "ct_001",
   "company_id": "c_049",
   "name": "macpac.co.nz  · macpac.com.au",
   "role": "",
   "email": "",
   "phone": "",
   "social": "",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_002",
   "company_id": "c_050",
   "name": "ultralightgear.com.au",
   "role": "",
   "email": "",
   "phone": "",
   "social": "",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_003",
   "company_id": "c_052",
   "name": "adventuremerchants.com",
   "role": "",
   "email": "",
   "phone": "",
   "social": "",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_004",
   "company_id": "c_058",
   "name": "ozoffroad.com.au",
   "role": "",
   "email": "",
   "phone": "",
   "social": "",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_005",
   "company_id": "c_059",
   "name": "blackhawkoutdoor.com.au",
   "role": "",
   "email": "",
   "phone": "",
   "social": "",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_008",
   "company_id": "c_005",
   "name": "",
   "role": "销售/客服",
   "email": "info@jaxgoods.com",
   "phone": "(720)266-6160",
   "social": "@jaxgoods",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_009",
   "company_id": "c_004",
   "name": "",
   "role": "采购总监/Buyer",
   "email": "info@neptunemountaineering.com",
   "phone": "(303)499-8866",
   "social": "@neptunemountaineering",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_010",
   "company_id": "c_007",
   "name": "",
   "role": "采购总监/Buyer",
   "email": "info@mtnhws.com",
   "phone": "(530)587-4844 (Donner Pass店)",
   "social": "@mountainhardwaresports",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_013",
   "company_id": "c_006",
   "name": "",
   "role": "销售/客服",
   "email": "fosteroutdoor@gmail.com",
   "phone": "(503)327-8463",
   "social": "@foster_outdoor",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_014",
   "company_id": "c_001",
   "name": "",
   "role": "采购总监/Buyer",
   "email": "answers@mountainshop.net",
   "phone": "(503) 288-6768",
   "social": "FB Mountain Shop",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_015",
   "company_id": "c_002",
   "name": "",
   "role": "采购专员/Assistant",
   "email": "sales@ascentoutdoors.com",
   "phone": "(206)545-8810",
   "social": "@ascent.outdoors",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_016",
   "company_id": "c_003",
   "name": "",
   "role": "决策人/老板/Owner",
   "email": "info@liveferal.com",
   "phone": "(303) 903-8584 (Denver) / (616) 326-0091 (Grand Rapids)",
   "social": "@Feral       FB Feral",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_017",
   "company_id": "c_008",
   "name": "",
   "role": "决策人/老板/Owner",
   "email": "happyhikerlife@gmail.com",
   "phone": "(575) 914-6644",
   "social": "@happyhikernm",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_018",
   "company_id": "c_009",
   "name": "",
   "role": "决策人/老板/Owner",
   "email": "heather@slimpickinsoutfitters.com",
   "phone": "(254)434-4677",
   "social": "@spoutfitter",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_025",
   "company_id": "c_010",
   "name": "",
   "role": "采购总监/Buyer",
   "email": "info@packratoc.com",
   "phone": "(479) 521-6340",
   "social": "@packratoc",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_027",
   "company_id": "c_011",
   "name": "",
   "role": "销售/客服",
   "email": "hello@trailful.com",
   "phone": "(706) 521-4453",
   "social": "@trailful",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_028",
   "company_id": "c_012",
   "name": "",
   "role": "销售/客服",
   "email": "info@jhoutdoors.com",
   "phone": "(859) 278-0730",
   "social": "@jhoutdoors1972",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_034",
   "company_id": "c_013",
   "name": "",
   "role": "采购总监/Buyer",
   "email": "info@sportago.com",
   "phone": "(707) 963-9042",
   "social": "@sportago",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_035",
   "company_id": "c_014",
   "name": "",
   "role": "采购专员/Assistant",
   "email": "hello@prooflab.com",
   "phone": "415-380-8900",
   "social": "@prooflab",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  },
  {
   "id": "ct_036",
   "company_id": "c_015",
   "name": "",
   "role": "决策人/老板/Owner",
   "email": "stokeddsm@gmail.com",
   "phone": "(515) 415-1057",
   "social": "@stokeddsm",
   "level": "Unknown",
   "acquisition_method": "",
   "created_at": "2026-01-01"
  }
 ],
 "activities": [
  {
   "id": "a_c_001_seed",
   "company_id": "c_001",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email、Contact Form",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_002_seed",
   "company_id": "c_002",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_003_seed",
   "company_id": "c_003",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_004_seed",
   "company_id": "c_004",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_005_seed",
   "company_id": "c_005",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_006_seed",
   "company_id": "c_006",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_007_seed",
   "company_id": "c_007",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_008_seed",
   "company_id": "c_008",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_009_seed",
   "company_id": "c_009",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_010_seed",
   "company_id": "c_010",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_011_seed",
   "company_id": "c_011",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_012_seed",
   "company_id": "c_012",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_013_seed",
   "company_id": "c_013",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_014_seed",
   "company_id": "c_014",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_015_seed",
   "company_id": "c_015",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-07-02T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_038_seed",
   "company_id": "c_038",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Facebook、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_039_seed",
   "company_id": "c_039",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Facebook、Email",
   "kind": "outreach",
   "replyType": "human",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_040_seed",
   "company_id": "c_040",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Instagram、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": "拒绝",
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": "现在没有扩展品牌的想法，不感兴趣，不要再发信息"
  },
  {
   "id": "a_c_041_seed",
   "company_id": "c_041",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Instagram",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_042_seed",
   "company_id": "c_042",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Instagram",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_043_seed",
   "company_id": "c_043",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Instagram",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_044_seed",
   "company_id": "c_044",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Instagram",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_045_seed",
   "company_id": "c_045",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Instagram、Website",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_046_seed",
   "company_id": "c_046",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_047_seed",
   "company_id": "c_047",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_048_seed",
   "company_id": "c_048",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Instagram、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_049_seed",
   "company_id": "c_049",
   "contact_id": "ct_001",
   "flow_type": "outbound",
   "channel": "Facebook、Instagram、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-15-53T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_050_seed",
   "company_id": "c_050",
   "contact_id": "ct_002",
   "flow_type": "outbound",
   "channel": "Facebook、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_051_seed",
   "company_id": "c_051",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-16-15T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_052_seed",
   "company_id": "c_052",
   "contact_id": "ct_003",
   "flow_type": "outbound",
   "channel": "Facebook、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_053_seed",
   "company_id": "c_053",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Facebook、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_054_seed",
   "company_id": "c_054",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Facebook、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_055_seed",
   "company_id": "c_055",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Facebook、Instagram、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_056_seed",
   "company_id": "c_056",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Facebook、Instagram、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_057_seed",
   "company_id": "c_057",
   "contact_id": null,
   "flow_type": "outbound",
   "channel": "Facebook、Instagram、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_058_seed",
   "company_id": "c_058",
   "contact_id": "ct_004",
   "flow_type": "outbound",
   "channel": "Facebook、Instagram、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  },
  {
   "id": "a_c_059_seed",
   "company_id": "c_059",
   "contact_id": "ct_005",
   "flow_type": "outbound",
   "channel": "Facebook、Email",
   "kind": "outreach",
   "replyType": "none",
   "replyReason": null,
   "sentiment": null,
   "at": "2026-01-01T00:00:00",
   "round_id": null,
   "note": ""
  }
 ],
 "inbound_leads": [
  {
   "id": "IN-001",
   "received_at": "2026-01-01",
   "country": "土耳其",
   "company": "https://www.instagram.com/sonsuzkamp/",
   "company_handle": "sonsuzkamp",
   "contact": "9055346106013",
   "source_platform": "Instagram",
   "original_message": "你好，我对面向伊拉克市场的露营产品很感兴趣。我正在宣召高质量的产品和配件。请问能否提供以下信息：“批发价格表，最低起订量，产品目录，运送到伊拉克的运输方式，是否可以混批？”我希望能建立长期的业务合作关系。如果产品和价格合适，我会定期订购",
   "need_type": [
    "批发",
    " 价格咨询",
    " 产品册咨询",
    " 合作咨询"
   ],
   "first_reply": null,
   "need_discovery": "在伊朗和土耳其有仓库，正在拓展产品线，之前买过山趣的产品对质量很满意，对小件的露营装备感兴趣，比如露营灯、小炉子、IGT桌。",
   "our_handling": "",
   "inbound_status": "New",
   "last_contact": "2026-08-01",
   "follow_up_count": 0,
   "next_action": "",
   "lost_reason": "客户不回复",
   "lead_owner": "时菊",
   "assigned_by": "陈晨",
   "assigned_at": "2026-01-01T00:00:00",
   "note": ""
  },
  {
   "id": "IN-002",
   "received_at": "2026-01-01",
   "country": "埃及",
   "company": "https://www.facebook.com/ayman.alrefaee",
   "company_handle": "ayman.alrefaee",
   "contact": "201009595657",
   "source_platform": "Facebook",
   "original_message": "",
   "need_type": [
    "产品册咨询"
   ],
   "first_reply": null,
   "need_discovery": "之前都是进美国的品牌，8月底要来中国广州，想来山趣，需要性价比高的产品",
   "our_handling": "",
   "inbound_status": "New",
   "last_contact": "2026-08-24",
   "follow_up_count": 0,
   "next_action": "",
   "lost_reason": "计划先参观仓库",
   "lead_owner": "时菊",
   "assigned_by": "陈晨",
   "assigned_at": "2026-01-01T00:00:00",
   "note": ""
  },
  {
   "id": "IN-003",
   "received_at": "2026-01-01",
   "country": "印度",
   "company": "https://www.facebook.com/satyajit.sarker.1",
   "company_handle": "satyajit.sarker.1",
   "contact": "919341440444",
   "source_platform": "Facebook",
   "original_message": "我对贵公司的产品感兴趣，我们如何联系？",
   "need_type": [
    "合作咨询"
   ],
   "first_reply": null,
   "need_discovery": "在找一整套大尺寸的IGT桌（沥水篮、收纳袋、炉头），旋转的露营椅，车载帐篷",
   "our_handling": "",
   "inbound_status": "New",
   "last_contact": null,
   "follow_up_count": 0,
   "next_action": "",
   "lost_reason": "产品不匹配",
   "lead_owner": "时菊",
   "assigned_by": "陈晨",
   "assigned_at": "2026-01-01T00:00:00",
   "note": ""
  },
  {
   "id": "IN-004",
   "received_at": "2026-01-01",
   "country": "伊朗",
   "company": "https://www.instagram.com/camp.video/",
   "company_handle": "camp.video",
   "contact": "989372521444",
   "source_platform": "Instagram",
   "original_message": "我是一名伊朗的商人、进口商、分销商和登山领队，如果你有生产这些装备，请把地址和联系方式发给我",
   "need_type": [
    "合作咨询",
    " 产品咨询",
    " 价格咨询"
   ],
   "first_reply": null,
   "need_discovery": "售卖轻量化的登山装备，是登山教练，有线下店铺，10月底-11月初参加广交会，会在中国待一个月",
   "our_handling": "",
   "inbound_status": "New",
   "last_contact": "2026-08-27",
   "follow_up_count": 0,
   "next_action": "",
   "lost_reason": "",
   "lead_owner": "时菊",
   "assigned_by": "陈晨",
   "assigned_at": "2026-01-01T00:00:00",
   "note": ""
  },
  {
   "id": "IN-017",
   "received_at": "2026-08-24",
   "country": "德国",
   "company": "https://www.facebook.com/roy.borner",
   "company_handle": "roy.borner",
   "contact": "4915783513635",
   "source_platform": "Facebook",
   "original_message": "您好，我在德国经营一家网店，对贵公司的产品很感兴趣。请问贵公司有产品目录和\n价格表吗?谢谢，此致敬礼。",
   "need_type": [
    "批发",
    " 价格咨询",
    " 产品册咨询"
   ],
   "first_reply": "2026-08-25",
   "need_discovery": "",
   "our_handling": "",
   "inbound_status": "New",
   "last_contact": "2026-08-27",
   "follow_up_count": 0,
   "next_action": "",
   "lost_reason": "",
   "lead_owner": "时菊",
   "assigned_by": "陈晨",
   "assigned_at": "2026-08-24T00:00:00",
   "note": "8.25凌晨回复，发信息的时间点调整晚上8点以后"
  },
  {
   "id": "IN-018",
   "received_at": "2026-08-24",
   "country": "美国",
   "company": "https://www.instagram.com/agev.vega/",
   "company_handle": "agev.vega",
   "contact": "1117862187831",
   "source_platform": "Instagram",
   "original_message": "您好，请问你们提供批发价格吗,谢谢",
   "need_type": [
    "批发",
    " 价格咨询"
   ],
   "first_reply": null,
   "need_discovery": "",
   "our_handling": "",
   "inbound_status": "New",
   "last_contact": "2026-08-26",
   "follow_up_count": 0,
   "next_action": "",
   "lost_reason": "",
   "lead_owner": "时菊",
   "assigned_by": "陈晨",
   "assigned_at": "2026-08-24T00:00:00",
   "note": ""
  },
  {
   "id": "IN-019",
   "received_at": "2026-08-27",
   "country": "美国",
   "company": "https://www.instagram.com/icebathusa/",
   "company_handle": "icebathusa",
   "contact": "14087053551",
   "source_platform": "Instagram",
   "original_message": "我们如何订购样品",
   "need_type": [
    "订购样品"
   ],
   "first_reply": "2026-08-28",
   "need_discovery": "主卖冷浴设备",
   "our_handling": "",
   "inbound_status": "Qualified",
   "last_contact": "2026-08-28",
   "follow_up_count": 0,
   "next_action": "",
   "lost_reason": "",
   "lead_owner": "时菊",
   "assigned_by": "陈晨",
   "assigned_at": "2026-08-27T00:00:00",
   "note": ""
  }
 ],
 "daily_rhythm": [
  {
   "id": "d_2026-08-26",
   "date": "2026-08-26",
   "schedule": "11:30–12:30 新客户开发；13:30–15:00 新客户开发；15:00–17:00 老客户回复；17:00–17:30 销售问题表",
   "interruption": "无",
   "result": "找8个客户，1个真人回复，对方无兴趣",
   "feeling": "澳洲开发回复率低",
   "adjustment": "继续测试当前节奏",
   "worker": ""
  },
  {
   "id": "d_2026-08-27",
   "date": "2026-08-27",
   "schedule": "8.30-9.30社媒发视频，回看客户信息；\n9:30-10:：30新客户开发；\n10：30-11:00老客户回复；\n11:40-12.30新客户开发；\n13：30-14:00新客户开发；\n14:00-17:00老客户回复;\n17:00-17:30销售问题表",
   "interruption": "11:00-11：40小会议",
   "result": "找6个客户，1个自动回复",
   "feeling": "Facebook大多是公共主页，不能发信息，只能通过邮箱或ins发送，但不会回复；",
   "adjustment": "利用现有的Facebook、instgram、谷歌邮箱三个平台开发，找到直接的采购商、或者负责人",
   "worker": ""
  },
  {
   "id": "d_2026-08-28",
   "date": "2026-08-28",
   "schedule": "8:30-10:00 社媒发视频，in客户回复；\n10：00-12:00 out客户开发；",
   "interruption": "",
   "result": "",
   "feeling": "",
   "adjustment": "",
   "worker": ""
  }
 ],
 "workers": [
  {
   "id": "w_陈晨",
   "name": "陈晨",
   "role": "主管",
   "outbound_count": 15,
   "inbound_count": 0
  },
  {
   "id": "w_时菊",
   "name": "时菊",
   "role": "业务员",
   "outbound_count": 22,
   "inbound_count": 7
  }
 ],
 "follow_up_tasks": [],
 "rounds": [],
 "customOptions": {
  "sourceMethod": [],
  "customerType": [],
  "channels": [],
  "replyReason": [],
  "stuckAt": [],
  "inboundNeedType": []
 },
 "frontline_events": []
}
